#!/sbin/busybox sh

# get values from profile
PROFILE=$(cat /data/.gabriel/.active.profile);
. /data/.gabriel/"$PROFILE".profile;

if [ "$crontab" == "on" ]; then
	if [ "$(pidof crond | wc -l)" -eq "0" ]; then
		$BB nohup $BB sh /res/crontab_service/service.sh > /dev/null 2>&1;
	fi;
fi;

CRON_SERVICE=$(pidof crond | wc -l);
if [ "$CRON_SERVICE" -eq "1" ]; then
	echo "Service is ONLINE and supported";
else
	echo "Service is OFFLINE or NOT supported";
fi;
