#!/sbin/busybox sh

# $1 - "default_zz_profile"
# $2 - value=
# Created By Dorimanx

# get values from profile
PROFILE=$(cat /data/.gabriel/.active.profile);
. /data/.gabriel/"$PROFILE".profile;

if [ "a$2" != "a" ]; then
	default_zz_profile=$2;

	echo "$default_zz_profile" > /sys/devices/system/cpu/cpufreq/zzmoove/profile_number;
	if [ -e /res/uci_boot.sh ]; then
		/res/uci_boot.sh power_mode $power_mode > /dev/null;
	else
		/res/uci.sh power_mode $power_mode > /dev/null;
	fi;
fi;

echo ${default_cpu0_gov};
